-- Migration 001: Create core tables for ESP32 water monitoring

create table if not exists public.water_readings (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  flow_rate_1 numeric(10,2) not null default 0 check (flow_rate_1 >= 0),
  flow_rate_2 numeric(10,2) not null default 0 check (flow_rate_2 >= 0),
  percentage_loss numeric(6,2) not null default 0 check (percentage_loss >= 0 and percentage_loss <= 100),
  water_level numeric(10,2) not null default 0 check (water_level >= 0),
  valve_state smallint not null default 0 check (valve_state in (0, 1)),
  leak_status text not null default 'Normal' check (leak_status in ('Normal', 'Warning', 'Critical')),
  anomaly_status text not null default 'Learning',
  system_online smallint not null default 1 check (system_online in (0, 1)),
  daily_total_liters numeric(12,3) not null default 0 check (daily_total_liters >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  alert_type text not null,
  message text not null,
  severity text not null default 'medium' check (severity in ('low', 'medium', 'high', 'critical')),
  created_at timestamptz not null default now()
);
